/*---------------------------------------------------------------------
 *  NAME:     hailstones.c
 *  AUTHOR:   Mu-Fen Hsieh
 *  DATE:     July 26, 2006
 *  PURPOSE:  A program which generates some hailstones
 *---------------------------------------------------------------------*/
#include <stdio.h>

/* Function Prototype */
void hailstones(long n);

int main(void) {
  long n;

  do {
    printf("Please enter n0: ");
  } while (scanf("%ld",&n)!=1 || n<=0);

  hailstones(n);

  return 0;
}

/*---------------------------------------------------------------------
 *  NAME:     hailstones
 *  PURPOSE:  compute and print the hailstone sequence generated by n
 *  PARMS:    n: the given positive integer to generate hailstones
 *  OUTPUT:   void
 *---------------------------------------------------------------------*/
void hailstones(long n) {
  int count = 2;

  printf("Hailstones generated by %d:\n\n",n);
  printf("%12d",n);
  
  while (n!=1) {
    if (n % 2==0)
      n /= 2;
    else
      n = n * 3 + 1;

    printf("%12d",n);
    if (count % 6 == 0) printf("\n");
    ++count;
  }
  
  --count;
  if (count % 6 != 0) printf("\n");
  printf("\nNumber of hailstones generated: %d\n",count);
}
